import { dbPromise } from "./IndexDB";

const masuk = [
  {
    id: "1",
    nama: "Nasi Goreng",
    harga: 15000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "2",
    nama: "Ayam Bakar",
    harga: 20000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "3",
    nama: "Es Teh Manis",
    harga: 5000,
    kategori: "minuman",
    gambar: "",
  },  
  {
    id: "4",
    nama: "Jus Alpukat",
    harga: 12000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "5",
    nama: "Mie Goreng",
    harga: 13000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "6",
    nama: "Sate Ayam",
    harga: 18000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "7",
    nama: "Soto Ayam",
    harga: 16000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "8",
    nama: "Bakso",
    harga: 14000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "9",
    nama: "Teh Tawar",
    harga: 3000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "10",
    nama: "Jus Jeruk",
    harga: 10000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "11",
    nama: "Nasi Uduk",
    harga: 14000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "12",
    nama: "Nasi Kuning",
    harga: 15000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "13",
    nama: "Kopi Hitam",
    harga: 8000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "14",
    nama: "Teh Tarik",
    harga: 9000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "15",
    nama: "Rendang",
    harga: 25000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "16",
    nama: "Ikan Bakar",
    harga: 22000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "17",
    nama: "Jus Mangga",
    harga: 11000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "18",
    nama: "Es Campur",
    harga: 13000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "19",
    nama: "Sop Buntut",
    harga: 30000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "20",
    nama: "Sate Kambing",
    harga: 24000,
    kategori: "makanan",
    gambar: "",
  },
  {
    id: "21",
    nama: "Pentol",
    harga: 5000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "22",
    nama: "Siomay",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "23",
    nama: "Cilok",
    harga: 4000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "24",
    nama: "Keripik Kentang",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "25",
    nama: "Keripik Pisang",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "26",
    nama: "Tahu Bulat",
    harga: 5000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "27",
    nama: "Bakwan",
    harga: 4000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "28",
    nama: "Pisang Goreng",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "29",
    nama: "Cireng",
    harga: 5000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "30",
    nama: "Cimol",
    harga: 5000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "31",
    nama: "Es Cincau",
    harga: 7000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "32",
    nama: "Es Doger",
    harga: 9000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "33",
    nama: "Es Teler",
    harga: 12000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "34",
    nama: "Jus Jambu",
    harga: 9000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "35",
    nama: "Jus Sirsak",
    harga: 10000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "36",
    nama: "Jus Melon",
    harga: 9000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "37",
    nama: "Jus Wortel",
    harga: 9000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "38",
    nama: "Jus Tomat",
    harga: 9000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "39",
    nama: "Jus Apel",
    harga: 10000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "40",
    nama: "Jus Strawberry",
    harga: 12000,
    kategori: "minuman",
    gambar: "",
  },
  {
    id: "41",
    nama: "Martabak Manis",
    harga: 15000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "42",
    nama: "Martabak Telur",
    harga: 18000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "43",
    nama: "Roti Bakar",
    harga: 10000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "44",
    nama: "Donat",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "45",
    nama: "Kue Cubit",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "46",
    nama: "Kue Lumpur",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "47",
    nama: "Klepon",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "48",
    nama: "Lemper",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "49",
    nama: "Pastel",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "50",
    nama: "Risoles",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "51",
    nama: "Sosis Solo",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "52",
    nama: "Bolu Kukus",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "53",
    nama: "Brownies",
    harga: 12000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "54",
    nama: "Puding Coklat",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "55",
    nama: "Puding Mangga",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "56",
    nama: "Puding Susu",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "57",
    nama: "Kacang Goreng",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "58",
    nama: "Kacang Atom",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "59",
    nama: "Kacang Disco",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "60",
    nama: "Kerupuk Udang",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "61",
    nama: "Kerupuk Ikan",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "62",
    nama: "Kerupuk Kulit",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "63",
    nama: "Kerupuk Bawang",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "64",
    nama: "Kerupuk Gendar",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "65",
    nama: "Kerupuk Rambak",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "66",
    nama: "Kerupuk Puli",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "67",
    nama: "Kerupuk Mie",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "68",
    nama: "Kerupuk Melarat",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "69",
    nama: "Kerupuk Jengkol",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "70",
    nama: "Kerupuk Tempe",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "71",
    nama: "Kerupuk Singkong",
    harga: 6000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "72",
    nama: "Kerupuk Kentang",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "73",
    nama: "Kerupuk Bawang Putih",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "74",
    nama: "Kerupuk Bawang Merah",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "75",
    nama: "Kerupuk Bawang Bombay",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "76",
    nama: "Kerupuk Bawang Daun",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "77",
    nama: "Kerupuk Bawang Seledri",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "78",
    nama: "Kerupuk Bawang Keju",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "79",
    nama: "Kerupuk Bawang Pedas",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "80",
    nama: "Kerupuk Bawang Manis",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "81",
    nama: "Kerupuk Bawang Asin",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "82",
    nama: "Kerupuk Bawang Gurih",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "83",
    nama: "Kerupuk Bawang Original",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "84",
    nama: "Kerupuk Bawang Spesial",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "85",
    nama: "Kerupuk Bawang Premium",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "86",
    nama: "Kerupuk Bawang Super",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "87",
    nama: "Kerupuk Bawang Extra",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "88",
    nama: "Kerupuk Bawang Jumbo",
    harga: 10000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "89",
    nama: "Kerupuk Bawang Mini",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "90",
    nama: "Kerupuk Bawang Kecil",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "91",
    nama: "Kerupuk Bawang Besar",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "92",
    nama: "Kerupuk Bawang Sedang",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "93",
    nama: "Kerupuk Bawang Tipis",
    harga: 7000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "94",
    nama: "Kerupuk Bawang Tebal",
    harga: 8000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "95",
    nama: "Kerupuk Bawang Renyah",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "96",
    nama: "Kerupuk Bawang Lembut",
    harga: 9000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "97",
    nama: "Kerupuk Bawang Gurih Spesial",
    harga: 10000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "98",
    nama: "Kerupuk Bawang Pedas Spesial",
    harga: 10000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "99",
    nama: "Kerupuk Bawang Manis Spesial",
    harga: 10000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "100",
    nama: "Kerupuk Bawang Asin Spesial",
    harga: 10000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "101",
    nama: "Kerupuk Bawang Original Spesial",
    harga: 10000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "102",
    nama: "Kerupuk Bawang Super Spesial",
    harga: 11000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "103",
    nama: "Kerupuk Bawang Premium Spesial",
    harga: 11000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "104",
    nama: "Kerupuk Bawang Extra Spesial",
    harga: 11000,
    kategori: "cemilan",
    gambar: "",
  },
  {
    id: "105",
    nama: "Kerupuk Bawang Jumbo Spesial",
    harga: 12000,
    kategori: "cemilan",
    gambar: "",
  },
];

export async function seedProduk() {
  const db = await dbPromise;
  for (const produk of masuk) {
   
    const existing = await db.get("produk", produk.id);
    if (!existing) {
      await db.add("produk", produk);
    }
  }
  console.log("Seed produk selesai!");
}
